export { default as Sprite } from './Sprite.js'
export { default as Cube } from './Cube.js'
export { default as Coffin } from './Coffin.js'
export { default as Sphere } from './Sphere.js'
export { default as Pyramid } from './Pyramid.js'